version: '2.3'
services:
  sqlair-bench:
    image: jujusolutions/sqlair-bench:latest
    build:
      context: ../..
      dockerfile: ./sqlair/bench/Dockerfile
    ports:
      - 3333:3333
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
